#! /bin/sh
# /etc/init.d/garagestreamer

### BEGIN INIT INFO
# Provides:          garagestreamer
# Required-Start:    none
# Required-Stop:     none
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts garagestreamer
# Description:       garagestreamer starts mjpg-streamer
#                    app to stream Raspberry Pi camera
### END INIT INFO

OUT_LOG=/dev/null

start() {
    echo "Starting garagestreamer"
    export LD_LIBRARY_PATH=/root/workspace/mjpg-streamer/mjpg-streamer-experimental
    if [ ! -d "${LD_LIBRARY_PATH}" ]; then
      echo "LD_LIBRARY_PATH: ${LD_LIBRARY_PATH} not a valid directory, exiting."
      exit 1
    fi
    cd "${LD_LIBRARY_PATH}" || exit
    ./mjpg_streamer \
      -o "output_http.so \
      -w ./www" \
      -i "input_raspicam.so \
      -x 1280 \
      -y 720 \
      -fps 15 \
      -ex night \
      -rot 270" \
      1> "${OUT_LOG}" 2>"${OUT_LOG}" &
}

stop() {
    echo "Stopping garagestreamer"
    killall -w -q mjpg_streamer
}

case "$1" in
  start)
    start
     ;;
  stop)
    stop
    ;;
  restart)
    stop && start
    ;;
  *)
    echo "Usage: /etc/init.d/garagestreamer {start|stop|restart}"
    exit 1
    ;;
  esac
exit 0
